#!/bin/bash

#getinput "thecode" > student/student_code.py
python3 -c "from inginious import input; print(input.get_input('thecode')['code'])" > student/student_code.py
output=$(run_student python3 student/student_code.py)

if [ "$output" = "Hello World!" ]; then
    feedback-result success
else
    feedback-result failed
    feedback-msg -em "Your program displayed : $output"
fi